Vagrant.configure('2') do |config|
    config.vm.box = 'generic/fedora27'
    config.vm.box_check_update = true
    (1..3).each do |i|
      config.vm.define "master#{i}" do |subconfig|
        subconfig.vm.hostname = "master#{i}"
        subconfig.vm.network :private_network, ip: "192.168.1.#{i + 10}"
        subconfig.hostmanager.enabled = true
        subconfig.hostmanager.manage_host = true
        subconfig.hostmanager.manage_guest = true
        subconfig.hostmanager.ignore_private_ip = false
        subconfig.hostmanager.include_offline = true
        subconfig.vm.provision "shell", inline: "systemctl stop firewalld;systemctl disable firewalld; systemctl mask firewalld"
        subconfig.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
        subconfig.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
        subconfig.vm.provision "shell", inline: "mkdir -p /root/.ssh /etc/salt/ssh && chmod 600 /home/vagrant/.ssh/id_rsa && cp -a /home/vagrant/.ssh/id_rsa* /root/.ssh && cp -a /home/vagrant/.ssh/id_rsa* /etc/salt/ssh && cat /home/vagrant/.ssh/id_rsa.pub | tee /root/.ssh/authorized_keys"
        subconfig.vm.provision "shell", inline: "dnf install -y python2-futures"
      end
    end
    (1..2).each do |i|
      config.vm.define "node#{i}" do |subconfig|
        subconfig.vm.hostname = "node#{i}"
        subconfig.vm.network :private_network, ip: "192.168.2.#{i + 10}"
        subconfig.hostmanager.enabled = true
        subconfig.hostmanager.manage_host = true
        subconfig.hostmanager.manage_guest = true
        subconfig.hostmanager.ignore_private_ip = false
        subconfig.hostmanager.include_offline = true
        subconfig.vm.provision "shell", inline: "systemctl stop firewalld;systemctl disable firewalld; systemctl mask firewalld"
        subconfig.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/.ssh/id_rsa.pub"
        subconfig.vm.provision "shell", inline: "mkdir -p /root/.ssh && cat /home/vagrant/.ssh/id_rsa.pub | tee /root/.ssh/authorized_keys"
        subconfig.vm.provision "shell", inline: "dnf install -y python2-futures"
      end
    end
end
